Repository skopjehacklab/sentence-collector, pull requests merged in 2020-04, with the labels that each got.

#1 Потсредена скрипта и README
  README.md
  extractor.py
  readme.md
  sentenceConventer.py
Labels: documentation, enhancement

#9 Провери дали реченицата содржи помалку од 2 збора
  extractor.py
Labels: enhancement, ready for a review

#10 Правила кој алатката ги следи
  README.md
Labels: documentation, enhancement, ready for a review

#11 Аутпут на stdout
  README.md
  extractor.py
Labels: documentation, enhancement

#13 Кратење на проверка
  extractor.py
Labels: ready for a review

#12 GitHub Action за тестирање на Алатката
  .github/workflows/pythonapp.yml
Labels: enhancement, ready for a review

#14 Додадени тестови
  extractor.py
  test_extractor.py
Labels: enhancement, ready for a review

#15 Замени ги скратениците со целосната верзија на зборот
  dictionary.json
  extractor.py
  requirements.txt
  test_extractor.py
Labels: ready for a review
